### ISSUE TITLE
A number of issued assertions on badgekit.org are 404ing

### ISSUE THREAD

**Issue by ottonomy** [mozilla/badgekit-api#134]
See:
 * http://api.badgekit.org/public/assertions/d6b003c993a8714b8dbbeff6a4c32a5a44fd160a
 * http://api.badgekit.org/public/assertions/887fd3e076b9495148295dbc5ef1a005cc101032
 * http://api.badgekit.org/public/assertions/89ee83b3ade482bd9dca292c14b2098e27d5cf43

The badgeclass and system are also returning 404 -- here are example URLs that correspond to the third assertion from the list above: 
 * http://api.badgekit.org/public/systems/openbadges-badges/badges/31eaff3ec4ad5227f061ef9dbfc94fb4
 * http://api.badgekit.org/public/systems/openbadges-badges

Hopefully this is not widespread or irreversible!

**Comment by ottonomy** [comment]
@simonwex Is there anybody with an hour this week to trace the source of this problem and check on these items in the database?

**Comment by simonwex** [comment]
@ottonomy until we get rolling on the improvements to this system, we don't have much expertise in this system. Think you could spend some time trying to figure out what we need to do on our end and then we can schedule some time with @jbuck to look into it?

**Comment by jbuck** [comment]
@ottonomy @simonwex I got it! http vs https. If you change those links to https, then everything appears to be working great.

The badgekit.org site is being hosted on http, and api.badgekit.org is being hosted on https. I'm willing to bet a misconfiguration when we transitioned badges to the new cluster.

**Comment by jbuck** [comment]
Hooray, changed the ELB listener and it appears to be working correctly now!

@ottonomy out of curiosity, do you know if the http version of these URLs is supposed to load the data directly, or should it do a redirect to the https URLs?

**Comment by jbuck** [comment]
Looking at the data returned in the badge assertions, looks it the http URL shouldn't redirect.

**Comment by ottonomy** [comment]
@jbuck Theoretically, a redirect should be fine. However, there are a bunch of HTTP libraries (like Android's default) that won't follow a redirect from HTTP -> HTTPS for some reason (The reverse makes complete sense. Never follow a redirect from HTTPS to downgrade to HTTP without the user's understanding and consent.)

Therefore, I'd lean toward serving the resource over HTTP if that's what was requested. 

Thanks for the fix @jbuck and @simonwex .
